### ISSUE TITLE
SizeOfRawData not being set in final PE in some cases.

### ISSUE THREAD

**Issue by Squiblydoo** [Squiblydoo/debloat#49]
A bug was found that impacts only tactic 7, "Bloat in PE section". The SizeOfRawData does not get set in the final PE with the result that the PE is malformed.

**Comment by lattaai4** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the check_section_compression function to update the SizeOfRawData of the biggest section after removing bloat. This ensures that the PE is not malformed when using tactic 7.

I also created pull request: https://github.com/Squiblydoo/debloat/pull/50


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by Squiblydoo** [comment]
Thanks, no thanks.

Fixed the issue myself in 1.6.2
